model: gemini/gemini-3-pro-preview
editor-model: gemini/gemini-2.5-pro
weak-model: gemini/gemini-2.5-flash

read:
  - CONVENTIONS.md
  - WORLD-BIBLE.md
  - TECH-BIBLE.md

# Auto-test command: Rebuild the wiki after edits
test-cmd: "npx quartz build"

# Force Aider to rewrite the entire file instead of trying to patch it.
# This prevents "SEARCH/REPLACE block failed" errors in Markdown.
edit-format: whole
